#name: Terraform Destroy for Static website
#
#on:
#  workflow_dispatch:
#    inputs:
#      bucket_name:
#        description: 'S3 Bucket name to destroy'
#        required: true
#        default: 'iec-mon'
#
#jobs:
#  terraform-destroy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: us-east-1
#
#      - name: Empty S3 bucket
#        run: aws s3 rm s3://${{ github.event.inputs.bucket_name }} --recursive
#
#      - name: Terraform Init
#        run: terraform init
#
#      - name: Terraform Destroy
#        run: terraform destroy -auto-approve -var="bucket_name=${{ github.event.inputs.bucket_name }}"