name: Terraform Deploy Static website

on:
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 Bucket name to create'
        required: true
        default: 'iec-mon'

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Temporarily disable S3 Block Public Access
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws s3control put-public-access-block \
            --account-id $ACCOUNT_ID \
            --public-access-block-configuration \
            BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${{ github.event.inputs.bucket_name }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="bucket_name=${{ github.event.inputs.bucket_name }}"

      - name: Re-enable S3 Block Public Access
        if: always()
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws s3control put-public-access-block \
            --account-id $ACCOUNT_ID \
            --public-access-block-configuration \
            BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
